apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    chart: example-helm
    repoURL: https://github.com/helm/examples
    helm:
      releaseName: hello-world
  destination:
    server: "https://kubernetes.default.svc"
    namespace: exampleappofapps1
